# General config
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

# GPIO config
CONFIG_GPIO=y

# UART config
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Modbus config
CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_CLIENT=y
#CONFIG_MODBUS_RAW_ADU=y
#CONFIG_MODBUS_NUMOF_RAW_ADU=1

# Network config
CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_DHCPV4=y

# Network address config
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_AUTO_INIT=y
CONFIG_NET_CONFIG_NEED_IPV4=y

# HTTP config
CONFIG_HTTP_SERVER=y
CONFIG_HTTP_PARSER=y
CONFIG_HTTP_PARSER_URL=y

# Net buffers config
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16
CONFIG_NET_BUF_RX_COUNT=64
CONFIG_NET_BUF_TX_COUNT=64

# Zephyr Shell config
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_KERNEL_SHELL=y
CONFIG_DEVICE_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_NET_SHELL=y

# Log config
CONFIG_NET_LOG=y
CONFIG_ETHERNET_LOG_LEVEL_DBG=y
CONFIG_MODBUS_LOG_LEVEL_DBG=y
CONFIG_UART_LOG_LEVEL_DBG=y
